PARSER_REQUEST_HEADER_USER_AGENT = 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)'
TRACKING_RESULT_PARCEL = 'parcel'
TRACKING_RESULT_TRACKS = 'tracks'
TRACKING_RESULT_COMPANY = 'company'

